import { useLoaderData, useFetcher } from "react-router";
import React from 'react';
// Route types are generated by react-router typegen; use any here to avoid build-time dependency
import { requireUserId } from "~/lib/auth.server";
import { db } from "~/lib/db.server";
import { PageWrapper } from "~/components/ui/page-wrapper";
import GearItem from '~/components/gear/gear-item';

export async function loader({ params, request }: any) {
  const userId = await requireUserId(request);
  const { listId } = params;
  if (!listId) throw new Response('Not Found', { status: 404 });

  const gearList = await db.gearList.findUnique({
    where: { id: listId },
    include: { gearItems: { orderBy: { createdAt: 'asc' } } },
  });

  if (!gearList) throw new Response('Not Found', { status: 404 });

  // Enrich gear items with claimer user info (counts per user)
  const allUserIds = new Set<string>();
  for (const it of gearList.gearItems) {
    (it.claimedByUserIds || []).forEach((id: string) => allUserIds.add(id));
  }

  const users = allUserIds.size > 0 ? await db.user.findMany({ where: { id: { in: Array.from(allUserIds) } }, select: { id: true, displayName: true, profilePhotoUrl: true } }) : [];
  const userMap = new Map(users.map(u => [u.id, u]));

  const enrichedItems = gearList.gearItems.map((it: any) => {
    const counts: Record<string, number> = {};
    (it.claimedByUserIds || []).forEach((id: string) => { counts[id] = (counts[id] || 0) + 1; });
    const claimedByUsers = Object.keys(counts).map(uid => ({ id: uid, displayName: userMap.get(uid)?.displayName || 'Someone', profilePhotoUrl: userMap.get(uid)?.profilePhotoUrl || null, quantity: counts[uid] }));
    return { ...it, claimedByUsers };
  });

  const enrichedGearList = { ...gearList, gearItems: enrichedItems };

  // Resolve participant user info
  const participantUsers = gearList.participantIds && gearList.participantIds.length > 0
    ? await db.user.findMany({ where: { id: { in: gearList.participantIds } }, select: { id: true, displayName: true, profilePhotoUrl: true } })
    : [];

  return { gearList: enrichedGearList, userId, participantUsers };
}

export default function GearDetails() {
  const { gearList, userId, participantUsers } = useLoaderData() as any;
  const isCreator = userId === gearList.creatorId;
  const fetcher = useFetcher();
  const [editing, setEditing] = React.useState(false);
  const [name, setName] = React.useState(gearList.name || '');
  const [description, setDescription] = React.useState(gearList.description || '');

  return (
    <PageWrapper maxWidth="4xl">
      <div className="mb-4 flex items-center justify-between">
        <h1 className="text-2xl font-bold text-primary">{gearList.name}</h1>
        <div className="text-sm text-secondary">{gearList.participantIds?.length || 0} participants</div>
      </div>

      <p className="text-sm text-secondary mb-4">{gearList.description}</p>

      <div className="space-y-3">
        {gearList.gearItems.map((item: any) => (
          <div key={item.id} className="flex items-start justify-between">
            <div className="flex-1">
              <GearItem item={item} gearListId={gearList.id} currentUserId={userId} />
            </div>
            {isCreator && (
              <div className="pl-3">
                <fetcher.Form method="post" action={`/api/gear/items/${item.id}/delete`}>
                  <button type="submit" className="text-sm text-danger">Remove</button>
                </fetcher.Form>
              </div>
            )}
          </div>
        ))}
      </div>

      <div className="mt-6 rounded bg-surface p-4">
        <h3 className="text-sm font-semibold text-primary mb-2">Participants</h3>
        <ParticipantList participants={participantUsers} currentUserId={userId} gearList={gearList} />
        {isCreator && (
          <div className="mt-3">
            <button onClick={() => setEditing((v) => !v)} className="text-sm text-primary mr-3">{editing ? 'Cancel' : 'Edit List'}</button>
            <fetcher.Form method="post" action={`/api/gear/${gearList.id}/delete`} className="inline-block">
              <button type="submit" className="text-sm text-danger">Delete List</button>
            </fetcher.Form>
          </div>
        )}
        <div className="mt-4">
          <AddParticipantForm gearListId={gearList.id} participantIds={gearList.participantIds || []} />
        </div>
      </div>

      {isCreator && editing && (
        <div className="mt-6 rounded bg-surface p-4">
          <h3 className="text-sm font-semibold text-primary mb-2">Edit List</h3>
          <fetcher.Form method="post" action={`/api/gear/${gearList.id}/edit`} className="space-y-3">
            <div>
              <input name="name" value={name} onChange={(e) => setName(e.target.value)} placeholder="List name" className="block w-full rounded border px-3 py-2" />
            </div>
            <div>
              <textarea name="description" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Description" className="block w-full rounded border px-3 py-2" />
            </div>
            <div>
              <button type="submit" className="rounded-lg btn-primary px-4 py-2">Save</button>
            </div>
          </fetcher.Form>
        </div>
      )}

      <div className="mt-6 rounded bg-surface p-4">
        <h3 className="text-sm font-semibold text-primary mb-2">Add Item</h3>
        {/* useFetcher prevents navigating to the API route (keeps action as resource-only) */}
        <AddItemForm gearListId={gearList.id} />
      </div>
    </PageWrapper>
  );
}

function AddItemForm({ gearListId }: { gearListId: string }) {
  const fetcher = useFetcher();

  return (
    <fetcher.Form method="post" action={`/api/gear/${gearListId}/items`} className="space-y-3">
      <div>
        <input name="itemName" placeholder="Item name" className="block w-full rounded border px-3 py-2" />
      </div>
      <div>
        <input name="quantityNeeded" type="number" defaultValue={1} min={1} className="block w-24 rounded border px-3 py-2" />
      </div>
      <div>
        <button type="submit" className="rounded-lg btn-primary px-4 py-2">{fetcher.state === 'submitting' ? 'Adding…' : 'Add'}</button>
      </div>
    </fetcher.Form>
  );
}

function AddParticipantForm({ gearListId, participantIds }: { gearListId: string, participantIds: string[] }) {
  const [queryState, setQueryState] = React.useState('');
  const [clientResults, setClientResults] = React.useState<any[]>([]);
  const [selectedUser, setSelectedUser] = React.useState<any | null>(null);
  const [submitting, setSubmitting] = React.useState(false);
  const debounceRef = React.useRef<number | null>(null);
  const abortRef = React.useRef<AbortController | null>(null);

  // Live-search users as queryState changes (debounced)
  React.useEffect(() => {
    if (debounceRef.current) window.clearTimeout(debounceRef.current);
    if (!queryState || queryState.length < 2) {
      setClientResults([]);
      return;
    }
    debounceRef.current = window.setTimeout(async () => {
      if (abortRef.current) abortRef.current.abort();
      abortRef.current = new AbortController();
      try {
        const res = await fetch(`/api/users/search?q=${encodeURIComponent(queryState)}`, {
          signal: abortRef.current.signal,
        });
        if (!res.ok) return;
        const data = await res.json();
        // exclude users already in participantIds
        const users = (data.users || []).filter((u: any) => !(participantIds || []).includes(u.id));
        setClientResults(users);
      } catch (err) {
        if ((err as any).name === 'AbortError') return;
        console.error('User search failed', err);
      }
    }, 250);

    return () => {
      if (debounceRef.current) window.clearTimeout(debounceRef.current);
      if (abortRef.current) abortRef.current.abort();
    };
  }, [queryState]);

  async function confirmAdd(userId: string) {
    setSubmitting(true);
    try {
      const res = await fetch(`/api/gear/${gearListId}/participants`, {
        method: 'POST',
        body: new URLSearchParams({ participantId: userId }),
      });
      if (res.ok) {
        window.location.reload();
      } else {
        const body = await res.json().catch(() => null);
        console.error('Add participant failed', body || await res.text());
        setSubmitting(false);
      }
    } catch (err) {
      console.error('Add participant error', err);
      setSubmitting(false);
    }
  }

  return (
    <div>
      {!selectedUser ? (
        <div>
          <div className="mb-2">
            <input
              value={queryState}
              onChange={(e) => setQueryState(e.target.value)}
              placeholder="Search users by name..."
              className="block w-full rounded border px-3 py-2"
              autoComplete="off"
            />
          </div>
          {clientResults.length > 0 && (
            <div className="space-y-2">
              {clientResults.map((user) => (
                <button
                  key={user.id}
                  onClick={() => setSelectedUser(user)}
                  className="flex w-full items-center space-x-3 rounded-lg p-3 text-left hover:bg-secondary"
                >
                  {user.profilePhotoUrl ? (
                    <img src={user.profilePhotoUrl} alt={user.displayName} className="h-10 w-10 rounded-full object-cover" />
                  ) : (
                    <div className="flex h-10 w-10 items-center justify-center rounded-full bg-accent text-surface">
                      {user.displayName[0].toUpperCase()}
                    </div>
                  )}
                  <span className="font-medium text-primary">{user.displayName}</span>
                </button>
              ))}
            </div>
          )}
          {queryState && clientResults.length === 0 && (
            <p className="text-sm text-muted">No users found matching "{queryState}"</p>
          )}
        </div>
      ) : (
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            {selectedUser.profilePhotoUrl ? (
              <img src={selectedUser.profilePhotoUrl} alt={selectedUser.displayName} className="h-10 w-10 rounded-full object-cover" />
            ) : (
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-accent text-surface">{selectedUser.displayName[0].toUpperCase()}</div>
            )}
            <div>
              <div className="font-medium">{selectedUser.displayName}</div>
              <div className="text-xs text-muted">{selectedUser.id}</div>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={() => setSelectedUser(null)} className="text-sm text-secondary">Change</button>
            <button onClick={() => confirmAdd(selectedUser.id)} disabled={submitting} className="rounded-lg btn-primary px-4 py-2">{submitting ? 'Adding…' : 'Add'}</button>
          </div>
        </div>
      )}
    </div>
  );
}

function ParticipantList({ participants, currentUserId, gearList }: any) {
  const fetcher = useFetcher();
  const isCreator = currentUserId === gearList.creatorId;

  return (
    <div className="space-y-2">
      {participants.length === 0 && <div className="text-sm text-secondary">No participants</div>}
      {participants.map((p: any) => (
        <div key={p.id} className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="text-sm">{p.displayName}</div>
            <div className="text-xs text-muted">{p.id}</div>
          </div>
          {isCreator && p.id !== gearList.creatorId && (
            <fetcher.Form method="post" action={`/api/gear/${gearList.id}/participants/${p.id}/remove`}>
              <button type="submit" className="text-sm text-danger">Remove</button>
            </fetcher.Form>
          )}
        </div>
      ))}
    </div>
  );
}
