import { useLoaderData, useFetcher } from "react-router";
import React from 'react';
// Route types are generated by react-router typegen; use any here to avoid build-time dependency
import { requireUserId } from "~/lib/auth.server";
import { db } from "~/lib/db.server";
import { PageWrapper } from "~/components/ui/page-wrapper";
import GearItem from '~/components/gear/gear-item';
import { formatDate } from "~/lib/date-utils";
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle } from "~/components/ui/dialog";
import { Button } from "~/components/ui/button";

export async function loader({ params, request }: any) {
  const userId = await requireUserId(request);
  const { listId } = params;
  if (!listId) throw new Response('Not Found', { status: 404 });

  const gearList = await db.gearList.findUnique({
    where: { id: listId },
    include: { gearItems: { orderBy: { createdAt: 'asc' } } },
  });

  if (!gearList) throw new Response('Not Found', { status: 404 });

  // Enrich gear items with claimer user info (counts per user)
  const allUserIds = new Set<string>();
  for (const it of gearList.gearItems) {
    (it.claimedByUserIds || []).forEach((id: string) => allUserIds.add(id));
  }

  const users = allUserIds.size > 0 ? await db.user.findMany({ where: { id: { in: Array.from(allUserIds) } }, select: { id: true, displayName: true, profilePhotoUrl: true } }) : [];
  const userMap = new Map(users.map(u => [u.id, u]));

  const enrichedItems = gearList.gearItems.map((it: any) => {
    const counts: Record<string, number> = {};
    (it.claimedByUserIds || []).forEach((id: string) => { counts[id] = (counts[id] || 0) + 1; });
    const claimedByUsers = Object.keys(counts).map(uid => ({ id: uid, displayName: userMap.get(uid)?.displayName || 'Someone', profilePhotoUrl: userMap.get(uid)?.profilePhotoUrl || null, quantity: counts[uid] }));
    return { ...it, claimedByUsers };
  });

  const enrichedGearList = { ...gearList, gearItems: enrichedItems };

  // Resolve participant user info
  const participantUsers = gearList.participantIds && gearList.participantIds.length > 0
    ? await db.user.findMany({ where: { id: { in: gearList.participantIds } }, select: { id: true, displayName: true, profilePhotoUrl: true } })
    : [];

  return { gearList: enrichedGearList, userId, participantUsers };
}

export default function GearDetails() {
  const { gearList, userId, participantUsers } = useLoaderData() as any;
  const isCreator = userId === gearList.creatorId;
  const fetcher = useFetcher();
  const [editing, setEditing] = React.useState(false);
  const [name, setName] = React.useState(gearList.name || '');
  const [description, setDescription] = React.useState(gearList.description || '');
  const prevFetcherStateRef = React.useRef<string>(fetcher.state);
  const [tripDate, setTripDate] = React.useState<string>(() => {
    if (!gearList.tripDate) return '';
    const d = new Date(gearList.tripDate);
    const yyyy = d.getFullYear();
    const mm = String(d.getMonth() + 1).padStart(2, '0');
    const dd = String(d.getDate()).padStart(2, '0');
    return `${yyyy}-${mm}-${dd}`;
  });

  React.useEffect(() => {
    if (prevFetcherStateRef.current === 'submitting' && fetcher.state === 'idle') {
      setEditing(false);
    }
    prevFetcherStateRef.current = fetcher.state;
  }, [fetcher.state]);

  return (
    <PageWrapper maxWidth="4xl">
      <div className="mb-4">
          <div className="flex items-center justify-between gap-5">
          <div className="flex-1">
            {!editing ? (
              <>
                <h1 className="text-2xl font-bold text-primary">{name}</h1>
                {gearList.tripDate && (
                  <div className="text-sm text-secondary">Trip date: {formatDate(gearList.tripDate)}</div>
                )}
                {description && (
                  <p className="text-sm text-secondary mb-4">{description}</p>
                )}
              </>
            ) : (
              <div className="space-y-3 w-full">
                <div>
                  <input name="name" value={name} onChange={(e) => setName(e.target.value)} placeholder="List name" className="block w-full rounded border px-3 py-2" />
                </div>
                <div>
                  <input type="date" name="tripDate" value={tripDate} onChange={(e) => setTripDate(e.target.value)} className="block rounded border px-3 py-2" />
                </div>
                <div>
                  <textarea name="description" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Description" className="block w-full rounded border px-3 py-2" />
                </div>
              </div>
            )}
          </div>
          <div className="flex items-center gap-3">

            <Dialog>
              <DialogTrigger asChild>
                <button className="text-sm text-secondary">{gearList.participantIds?.length || 0} participants</button>
              </DialogTrigger>
              <DialogContent className="max-w-md">
                <DialogHeader>
                  <DialogTitle>Participants</DialogTitle>
                </DialogHeader>
                <div className="mt-2">
                  <ParticipantList participants={participantUsers} currentUserId={userId} gearList={gearList} />
                  <div className="mt-4">
                    <AddParticipantForm gearListId={gearList.id} participantIds={gearList.participantIds || []} />
                  </div>
                </div>
              </DialogContent>
            </Dialog>
                        {isCreator && (
              <>
                {!editing ? (
                  <>
                    <button onClick={() => setEditing(true)} className="rounded-lg btn-primary px-3 py-2">Edit List</button>
                    <form method="post" action={`/api/gear/${gearList.id}/delete`}>
                      <button type="submit" className="rounded-lg btn-destructive px-3 py-2">Delete List</button>
                    </form>
                  </>
                ) : (
                  <>
                    <button
                      onClick={async (e) => {
                        e.preventDefault();
                        const body = new URLSearchParams();
                        body.append('name', name);
                        body.append('description', description);
                        body.append('tripDate', tripDate);
                        try {
                          const res = await fetch(`/api/gear/${gearList.id}/edit`, { method: 'POST', body });
                          if (res.ok) {
                            window.location.reload();
                          } else {
                            console.error('Save failed', await res.text());
                          }
                        } catch (err) {
                          console.error('Save error', err);
                        }
                      }}
                      className="rounded-lg btn-primary px-3 py-2"
                    >
                      Save
                    </button>
                    <button onClick={() => { setEditing(false); setName(gearList.name || ''); setDescription(gearList.description || ''); setTripDate(() => {
                      if (!gearList.tripDate) return '';
                      const d = new Date(gearList.tripDate);
                      const yyyy = d.getFullYear();
                      const mm = String(d.getMonth() + 1).padStart(2, '0');
                      const dd = String(d.getDate()).padStart(2, '0');
                      return `${yyyy}-${mm}-${dd}`;
                    }); }} className="rounded-lg px-3 py-2 text-sm text-secondary">Cancel</button>
                  </>
                )}
              </>
            )}
          </div>
        </div>
      </div>

      <div className="space-y-3">
        {gearList.gearItems.map((item: any) => (
          <div key={item.id} className="flex items-center bg-secondary rounded-lg p-4">
            {isCreator && (
              <div className="mr-3">
                <fetcher.Form method="post" action={`/api/gear/items/${item.id}/delete`}>
                  <button
                    type="submit"
                    aria-label="Remove item"
                    title="Remove item"
                    className="rounded-full btn-primary w-8 h-8 flex items-center justify-center"
                  >
                    ×
                  </button>
                </fetcher.Form>
              </div>
            )}
            <div className="flex-1">
              <GearItem item={item} gearListId={gearList.id} currentUserId={userId} />
            </div>
          </div>
        ))}
      </div>

      

      <div className="mt-6 rounded bg-surface p-4">
        <h3 className="text-sm font-semibold text-primary mb-2">Add Item</h3>
        {/* useFetcher prevents navigating to the API route (keeps action as resource-only) */}
        <AddItemForm gearListId={gearList.id} />
      </div>
    </PageWrapper>
  );
}

function AddItemForm({ gearListId }: { gearListId: string }) {
  const fetcher = useFetcher();

  return (
    <fetcher.Form method="post" action={`/api/gear/${gearListId}/items`} className="space-y-3">
      <div>
        <input name="itemName" placeholder="Item name" className="block w-full rounded border px-3 py-2" />
      </div>
      <div>
        <input name="quantityNeeded" type="number" defaultValue={1} min={1} className="block w-24 rounded border px-3 py-2" />
      </div>
      <div>
        <button type="submit" className="rounded-lg btn-primary px-4 py-2">{fetcher.state === 'submitting' ? 'Adding…' : 'Add'}</button>
      </div>
    </fetcher.Form>
  );
}

function AddParticipantForm({ gearListId, participantIds }: { gearListId: string, participantIds: string[] }) {
  const [queryState, setQueryState] = React.useState('');
  const [clientResults, setClientResults] = React.useState<any[]>([]);
  const [selectedUsers, setSelectedUsers] = React.useState<any[]>([]);
  const [submitting, setSubmitting] = React.useState(false);
  const [searching, setSearching] = React.useState(false);
  const lastQueryRef = React.useRef<string>('');
  const debounceRef = React.useRef<number | null>(null);
  const abortRef = React.useRef<AbortController | null>(null);

  // Live-search users as queryState changes (debounced)
  React.useEffect(() => {
    if (debounceRef.current) window.clearTimeout(debounceRef.current);
    if (!queryState || queryState.length < 2) {
      setClientResults([]);
      return;
    }
    debounceRef.current = window.setTimeout(async () => {
      if (abortRef.current) abortRef.current.abort();
      abortRef.current = new AbortController();
      setSearching(true);
      try {
        const res = await fetch(`/api/users/search?q=${encodeURIComponent(queryState)}`, {
          signal: abortRef.current.signal,
        });
        if (!res.ok) {
          setSearching(false);
          return;
        }
        const data = await res.json();
        // exclude users already in participantIds
        const users = (data.users || []).filter((u: any) => !(participantIds || []).includes(u.id));
        setClientResults(users);
        // mark that we've searched for this query
        lastQueryRef.current = queryState;
        setSearching(false);
      } catch (err) {
        if ((err as any).name === 'AbortError') return;
        console.error('User search failed', err);
        setSearching(false);
      }
    }, 250);

    return () => {
      if (debounceRef.current) window.clearTimeout(debounceRef.current);
      if (abortRef.current) abortRef.current.abort();
    };
  }, [queryState]);

  async function addSelected() {
    if (selectedUsers.length === 0) return;
    setSubmitting(true);
    try {
      const promises = selectedUsers.map((u) => fetch(`/api/gear/${gearListId}/participants`, {
        method: 'POST',
        body: new URLSearchParams({ participantId: u.id }),
      }));
      const results = await Promise.all(promises);
      const ok = results.every((r) => r.ok);
      if (ok) {
        window.location.reload();
      } else {
        console.error('One or more adds failed', results);
        setSubmitting(false);
      }
    } catch (err) {
      console.error('Add participants error', err);
      setSubmitting(false);
    }
  }

  return (
    <div>
      <div>
        <div className="mb-2">
          <input
            value={queryState}
            onChange={(e) => setQueryState(e.target.value)}
            placeholder="Search users by name..."
            className="block w-full rounded border px-3 py-2"
            autoComplete="off"
          />
        </div>

        {selectedUsers.length > 0 && (
          <div className="flex flex-wrap gap-2 mb-3">
            {selectedUsers.map((u) => (
              <div key={u.id} className="flex items-center gap-2 rounded-full bg-muted/20 px-3 py-1">
                {u.profilePhotoUrl ? (
                  <img src={u.profilePhotoUrl} alt={u.displayName} className="h-6 w-6 rounded-full object-cover" />
                ) : (
                  <div className="h-6 w-6 rounded-full bg-accent text-surface flex items-center justify-center text-xs">{u.displayName[0].toUpperCase()}</div>
                )}
                <span className="text-sm font-medium">{u.displayName}</span>
                <button onClick={() => setSelectedUsers((s) => s.filter(x => x.id !== u.id))} className="text-sm text-secondary">×</button>
              </div>
            ))}
          </div>
        )}

        {clientResults.length > 0 && (
          <div className="space-y-2">
            {clientResults.map((user) => (
              <button
                key={user.id}
                onClick={() => {
                  setSelectedUsers((s) => (s.find(x => x.id === user.id) ? s : [...s, user]));
                  setQueryState('');
                  setClientResults((r) => r.filter((x) => x.id !== user.id));
                }}
                className="flex w-full items-center space-x-3 rounded-lg p-3 text-left hover:bg-secondary"
              >
                {user.profilePhotoUrl ? (
                  <img src={user.profilePhotoUrl} alt={user.displayName} className="h-10 w-10 rounded-full object-cover" />
                ) : (
                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-accent text-surface">
                    {user.displayName[0].toUpperCase()}
                  </div>
                )}
                <span className="font-medium text-primary">{user.displayName}</span>
                <span className="text-xs text-muted ml-auto">Add</span>
              </button>
            ))}
          </div>
        )}

        {queryState && !searching && clientResults.length === 0 && lastQueryRef.current === queryState && (
          <p className="text-sm text-muted">No users found matching "{queryState}"</p>
        )}

        {!queryState && (
          <p className="text-sm text-muted">Type at least 2 characters to search for users</p>
        )}

        <div className="mt-3 flex items-center gap-2">
          <button onClick={addSelected} disabled={submitting || selectedUsers.length === 0} className="rounded-lg btn-primary px-4 py-2">{submitting ? 'Adding…' : `Add ${selectedUsers.length} user${selectedUsers.length !== 1 ? 's' : ''}`}</button>
          <button onClick={() => { setSelectedUsers([]); setQueryState(''); setClientResults([]); }} className="text-sm text-secondary">Clear</button>
        </div>
      </div>
    </div>
  );
}

function ParticipantList({ participants, currentUserId, gearList }: any) {
  const fetcher = useFetcher();
  const isCreator = currentUserId === gearList.creatorId;

  return (
    <div className="space-y-2">
      {participants.length === 0 && <div className="text-sm text-secondary">No participants</div>}
      {participants.map((p: any) => (
        <div key={p.id} className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            {p.profilePhotoUrl ? (
              <img src={p.profilePhotoUrl} alt={p.displayName} className="h-8 w-8 rounded-full object-cover" />
            ) : (
              <div className="h-8 w-8 rounded-full bg-accent text-surface flex items-center justify-center">{p.displayName[0].toUpperCase()}</div>
            )}
            <div className="text-sm">{p.displayName}</div>
          </div>
          {isCreator && p.id !== gearList.creatorId && (
            <fetcher.Form method="post" action={`/api/gear/${gearList.id}/participants/${p.id}/remove`}>
              <button type="submit" className="text-sm text-danger">Remove</button>
            </fetcher.Form>
          )}
        </div>
      ))}
    </div>
  );
}
